language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- 'iojs-v1.6.2'
services:
- mongodb
addons:
  code_climate:
    repo_token:
      secure: "kmN4GIE9O7uFtw4dCcJvrLitZFJmHPF0G8gCiHGEdK0HdK6xT9rTD8TjHXGM07QNB0Teyfwmtc32DKzO6hPgLGSGBjMiJlOUe5GKrz16a2k7QmbDF8t4jsptuwFKB+aKXmNVhJ8Pc7POlGoVxMd0wGfqeZ9lKLfG5pE+WSGkDxQ="
after_success: npm run codeclimate
