language: node_js
sudo: false
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: hannes@impossiblearts.com
  skip_cleanup: true
  api_key:
    secure: OyxBma7IJFkTphj8OIP/Dm9Df040EIWyTzmaRzH9p9qEUP1XOUgAoP6MWWM3kvTle47SdEVZxwtum4ePZdE1hqsPQ8JSkLb9yZCcT2RNADGmB6xPGEPSCf4aqvaJ61u1F2lk3p496hf8f/OcRaqbO9Bq29ed8wOXwRJ0/ZleBZw=
  on:
    branch: master
    repo: netiam/netiam
node_js:
- iojs-v2
services:
- mongodb
before_deploy:
- npm config set spin false --global
after_success:
- npm run build
- npm run test-coverage
- codeclimate < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: kmN4GIE9O7uFtw4dCcJvrLitZFJmHPF0G8gCiHGEdK0HdK6xT9rTD8TjHXGM07QNB0Teyfwmtc32DKzO6hPgLGSGBjMiJlOUe5GKrz16a2k7QmbDF8t4jsptuwFKB+aKXmNVhJ8Pc7POlGoVxMd0wGfqeZ9lKLfG5pE+WSGkDxQ=
env:
  global:
    secure: TxSMqm+QwN44Uxp0OUsrALSomXtvjJflILI+3sxB2RY1FUrKM+pbLfHaBWGjH5kbSMPdia1WFzBbLen1zrDdpA2Mo4/y+N6iX3ZSL9oR6xJCJJs16NUwJSU+UNMf/wxqcvlGSDbFr+i0+u6BVEFKyI0AHNUpOfKN3RxH/Y+pUoM=
notifications:
  email: false
  webhooks:
    urls:
    - https://jenkins.dovigo.org/view/netiam/job/netiam-site/build?token=$JENKINS_TOKEN
    on_success: always
    on_failure: never
    on_start: never
