language: node_js
sudo: false
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: hannes@impossiblearts.com
  skip_cleanup: true
  api_key:
    secure: CezJ96R0fVpiigEGJsY4bZyW5nre6S+t1uKxeDXnwBEpgCmzkMrThAX9g/C4YzMR8x2v/YNTeJPlRpEb0Vm61JCyIJmbLo/77lurwZ7AzT5e8Nd2I7qpeg+JWB27zLjygb7j0btRI4NJzAFvktXFVf/cwBiwYUq+phXZ4NzXGbM=
  on:
    branch: master
    repo: netiam/netiam
node_js:
- iojs-v2
services:
- mongodb
after_success:
- npm run build
- npm run test-coverage
- codeclimate < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: fiPhvy4r3erfWdNNKC3YfyJ2npIjtLXI480NaV3MlI/PAvFEQXO0SgqQEZy9gyKEOcAJXOwO/IG7yvC4oip6y6a+Vy6DIXKDGW43+2B3re7RJ8vY5cALp0ra6axWEopJ5Q55tiQtj6Ys/sBqRVLwu+px5SeATlGncfSmA2qKA/k=
env:
  global:
    secure: Pi2hUWJm01OCsJugGtjgotiG+BxQPWwkNqQLsWS0BV4UyIP6Cp3FnFUi0snkLcFkXC1cf7uVRboFyOYMeDxlsvedi9BEpPF/1+8AMLd7c6iyEBMNDrk4zffNA7xg+wuFRfTESpDrPQmTPilXxjr1+MajJWKdiFunnvjzWKKX4TM=
notifications:
  email: false
  webhooks:
    urls:
    - https://jenkins.dovigo.org/view/netiam/job/netiam-site/build?token=$JENKINS_TOKEN
    on_success: always
    on_failure: never
    on_start: never
